# Railway Configuration for Backend Deployment
# Place this file in the backend directory

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
ENVIRONMENT = "production"
DATABASE_URL = "${{ Railway.DATABASE_URL }}"
SECRET_KEY = "${{ Railway.SECRET_KEY }}"
ALLOWED_ORIGINS = "${{ Railway.ALLOWED_ORIGINS }}"

[networking]
serviceDomains = ["${{ RAILWAY_STATIC_URL }}"]